path:
    inp     : "input.txt"
    tar     : "target.txt"
    encoder : "encoder.pth"
    decoder : "decoder.pth"

cuda: 0

model:
    hidden  : 32
    layer   : 1
    dropout : 0.0

train:
    use_corpus_size : 1000
    batch_size      : 16
    learning_rate   : 0.01
    max_epoch       : 1000

test:
    beam_width  : 15
    min_length  : 2
    max_length  : 15
