path:
    inp     : "data/corpus/input.txt"
    tar     : "data/corpus/target.txt"
    encoder : "data/model/encoder.pth"
    decoder : "data/model/decoder.pth"

cuda: 0

model:
    hidden  : 32
    layer   : 1
    dropout : 0.0

train:
    use_corpus_size : -1
    batch_size      : 128
    learning_rate   : 0.0001
    max_epoch       : 300

test:
    beam_width  : 15
    min_length  : 2
    max_length  : 15
