path:
    inp     : "data/corpus/input.txt"
    tar     : "data/corpus/target.txt"
    encoder : "data/model/encoder_300.pth"
    decoder : "data/model/decoder_300.pth"

cuda: 0

model:
    hidden  : 256
    layer   : 3
    dropout : 0.2

train:
    use_corpus_size : -1
    batch_size      : 128
    learning_rate   : 0.0001
    max_epoch       : 300

test:
    beam_width  : 15
    min_length  : 2
    max_length  : 15
