path:
    pattern : "data/system/pattern.txt"
    romaji  : "data/system/romaji.txt"
    synonym : "data/system/synonym.txt"
    font    : "data/font/07LogoTypeGothic7.ttf"
    img     : "data/img/"
    text    : "data/text/"
