path:
    pattern     : "data/system/pattern.txt"
    romaji      : "data/system/romaji.txt"
    synonym     : "data/system/synonym.txt"
    map         : "data/map/edit.txt"
    ground_param: "data/map/ground_param.txt"
    object_param: "data/map/object_param.txt"
